name: Workflow B

on:
  create:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}        
        
      - name: Create Draft PR
        run: |
          # echo ${{ secrets.GH_PAT }} | gh auth login --with-token
          gh pr create --fill --draft
