name: Auto PR

on:
  push:
    branches-ignore:
      - main
  create:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}

      - name: Create Draft PR
        run: |
          # default to grabbing branch name from create trigger
          BRANCH_NAME=${{ github.event.ref }}
          if [ "${{ github.event_name }}" == "push" ] ; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            # sleep in case this was called at the same time as a branch create
            sleep 10s
          fi
          echo ${{ secrets.GH_PAT }} | gh auth login --with-token
          PR_EXISTS=$(gh pr list --json headRefName | jq --arg branch "$BRANCH_NAME" '.[] | select(.headRefName==$branch)')
          if [ -z "$PR_EXISTS" ] ; then

            # try to make a more user-friendly PR title
            # Change to lower case
            BRANCH_NAME=$(echo "$BRANCH_NAME" | awk '{print tolower($0)}')
            PR_TITLE=$(echo $BRANCH_NAME)
            # Regex on api-<num>-<text description>
            REGEX="api-([0-9]+)-(.+)"
            if  [[ $BRANCH_NAME =~ $REGEX ]] ;
            then
                # replace - with a space to make description more readable
                TITLE_TEXT=$(echo "${BASH_REMATCH[2]}" | tr - " ")
                PR_TITLE="[API-${BASH_REMATCH[1]}] - $TITLE_TEXT"
            fi
            gh pr create --title "$PR_TITLE" -F ./pull_request_template.md --draft
          fi
