name: Workflow B

on:
  create:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo  ${{ github.event.ref }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}        
        
