name: Auto PR

on:
  push:
  create:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
        
      - name: Create Draft PR
        run: |
          # default to grabbing branch name from create trigger
          BRANCH_NAME=${{ github.event.ref }}
          if [ "${{ github.event_name }}" == "push" ] ; then
            BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
            # sleep in case this was called at the same time as a branch create
            sleep 10s
          fi
          echo ${{ secrets.GH_PAT }} | gh auth login --with-token
          gh pr list
          echo "---"
          gh pr list --json headRefName
          echo "---"
          gh pr list --json headRefName | jq '.[]'
          echo "---"
          gh pr list --json headRefName | jq --arg branch "$BRANCH_NAME" '.[] | select(.headRefName=="$branch")'
          echo "---"
          PR_EXISTS=$(gh pr list --json headRefName | jq --arg branch "$BRANCH_NAME" '.[] | select(.headRefName==$branch)')
          if [ -z "$PR_EXISTS" ] ; then          
            gh pr create --title "$BRANCH_NAME" -F ./pull_request_template.md --draft
          fi
