name: Auto PR

on:
  push:
  create:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.ref }}
        
      - name: Create Draft PR from new branch
        if:  github.event_name == 'create'
        run: |
          echo ${{ secrets.GH_PAT }} | gh auth login --with-token
          gh pr create --title "${{ github.event.ref }}" -F ./pull_request_template.md --draft
          
      - name: Create Draft PR from existing branch
        if:  github.event_name == 'push'
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          echo ${{ secrets.GH_PAT }} | gh auth login --with-token
          PR_EXISTS=$(gh pr list --json headRefName | jq --arg branch "$BRANCH_NAME" '.[] | select(.headRefName=="$branch")')
          if [ -z "$PR_EXISTS" ]
          then          
            gh pr create --title "${{ github.event.ref }}" -F ./pull_request_template.md --draft
          fi
