name: Build and Push

on:
  workflow_dispatch:

jobs:
  build:
    env:
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-gov-west-1
      AWS_REGION: us-gov-west-1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Pull image
      run: |
        docker pull nginx:latest
        docker tag nginx:latest 367210624078.dkr.ecr.us-gov-west-1.amazonaws.com/rise8:latest
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 367210624078.dkr.ecr.us-gov-west-1.amazonaws.com
    - name: Build and push
      run: docker push 367210624078.dkr.ecr.us-gov-west-1.amazonaws.com/rise8:latest
