name: Spotify Random Song

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Song
        uses: ./.github/actions/random-spotify-song-from-playlist 
        id: spotify
        with:
          credentials: ${{ secrets.SPOTIFY_CREDENTIALS }}
          playlistId: 1yhasvKTi8wJMmpt1mj57J # Eric's Folk Metal Playlist          
          
      # Print info about a random song
      - name: Song Info
        run: |
          echo "The song is ${{ steps.spotify.outputs.song-name }} by ${{ steps.spotify.outputs.song-artist }}."
          echo "Check it out here:  ${{ steps.spotify.outputs.song-url }}"

      - name: Hello world action step 2
        uses: ./.github/actions/action2 # Uses an action in the root directory
        id: hello2
        with:
          who-to-greet: 'Someone Else'