name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Hello world action step
        uses: ./.github/actions/action1  # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
          
      - name: Hello world action step 2
        uses: ./.github/actions/action2 # Uses an action in the root directory
        id: hello2
        with:
          who-to-greet: 'Someone Else'
          
      # Use the output from the `hello` step
      - name: Get the output time
        run: |
          echo "The time was ${{ steps.hello.outputs.time }}"
          echo "The time was ${{ steps.hello2.outputs.time }}"
