name: Workflow A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Trigger next workflow
        run: |
          curl -H "Authorization: token ${{ secrets.REPO_PAT }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            "https://api.github.com/repos/ericbram/spotify-playlist-slacker/dispatches" \
            -d '{"event_type": "trigger-workflow-b", "client_payload": {"foo": "bar"}}'
