name: Workflow A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Trigger next workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-b
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
