name: Workflow A

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
#       - name: Trigger next workflow
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.REPO_GHA_PAT }}
#           repository: ${{ github.repository }}
#           event-type: trigger-workflow-2
#           client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Trigger next workflow
        run: |
          curl -H "Authorization: token ${{ secrets.REPO_GHA_PAT  }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            "https://api.github.com/repos/ericbram/spotify-playlist-slacker/dispatches" \
            -d '{"event_type": "trigger-workflow-2", "client_payload": {"foo": "bar"}}'
