name: boolean

on:
  workflow_dispatch:
    inputs:
      use-emoji:
        type: boolean
        description: Include 🎉🤣 emojis

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: one
        run: echo "starting"
      - name: Send greeting
        if: github.event.inputs.use-emoji == false
        run: echo "${{github.event.inputs.use-emoji}}"
