name: boolean

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true
        type: string
      deploy_target:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run driftctl
        run: |
          echo "${{ inputs.build_id }} - ${{github.event.inputs.deploy_target}}"
