name: boolean

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run driftctl
        uses: ebram-va/driftctl-action@main
        with:
          version: 0.22.0
          args: --from tfstate://test.tfstate --only-managed
