name: Workflow B

on:
  repository_dispatch:
    types: 
      - secrel-complete

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hi
        run: echo ${{ github.event.client_payload.development-image }}
